#!/usr/bin/env python3
"""Generate the Astro image manifest from the reviewed screenshot manifest."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
REVIEW = Path(__file__).resolve().parent / ".image-review"
TARGET = REPO / "src" / "data" / "guideImages.ts"
SLUG_REMAP = {"branch-account": "first-sign-in"}


def sanitize_caption(text: str) -> str:
    return (
        text.replace("xxx.xxx@incorp.asia", "user@example.com")
        .replace("xxx@incorp.asia", "user@example.com")
    )


def main() -> None:
    records = json.loads(
        (REVIEW / "published-manifest.json").read_text(encoding="utf-8")
    )
    grouped: dict[str, list[dict]] = defaultdict(list)
    for record in records:
        slug = SLUG_REMAP.get(record["slug"], record["slug"])
        caption = sanitize_caption(
            record["context"] or f'操作截图 {record["sequence"]}'
        )
        grouped[slug].append(
            {
                "src": record["public_path"],
                "alt": caption,
                "caption": caption,
                "source": record["document"],
            }
        )

    lines = [
        "// Generated by scripts/build_web_image_manifest.py. Do not edit by hand.",
        "export type GuideImage = {",
        "  src: string;",
        "  alt: string;",
        "  caption: string;",
        "  source: string;",
        "};",
        "",
        "export const guideImagesBySlug: Record<string, GuideImage[]> = "
        + json.dumps(grouped, ensure_ascii=False, indent=2)
        + ";",
        "",
    ]
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {TARGET} with {len(records)} images across {len(grouped)} guides")


if __name__ == "__main__":
    main()
