// Generated by scripts/build_web_image_manifest.py. Do not edit by hand.
export type GuideImage = {
  src: string;
  alt: string;
  caption: string;
  source: string;
};

export const guideImagesBySlug: Record<string, GuideImage[]> = {
  "install-m365": [
    {
      "src": "/assets/sop/install-m365/install-m365-86b832f-01.webp",
      "alt": "点击左上角下载按钮，等待下载完成",
      "caption": "点击左上角下载按钮，等待下载完成",
      "source": "1-1.安装M365应用套件.docx"
    },
    {
      "src": "/assets/sop/install-m365/install-m365-86b832f-02.webp",
      "alt": "解压缩获得应用安装包：",
      "caption": "解压缩获得应用安装包：",
      "source": "1-1.安装M365应用套件.docx"
    },
    {
      "src": "/assets/sop/install-m365/install-m365-86b832f-03.webp",
      "alt": "分别直接运行安装包，并等待完成即可。",
      "caption": "分别直接运行安装包，并等待完成即可。",
      "source": "1-1.安装M365应用套件.docx"
    },
    {
      "src": "/assets/sop/install-m365/install-m365-86b832f-04.webp",
      "alt": "分别直接运行安装包，并等待完成即可。",
      "caption": "分别直接运行安装包，并等待完成即可。",
      "source": "1-1.安装M365应用套件.docx"
    },
    {
      "src": "/assets/sop/install-m365/install-m365-86b832f-05.webp",
      "alt": "（可选）若不需要Microsoft Teams开机自动启动，请进入“设置”",
      "caption": "（可选）若不需要Microsoft Teams开机自动启动，请进入“设置”",
      "source": "1-1.安装M365应用套件.docx"
    },
    {
      "src": "/assets/sop/install-m365/install-m365-86b832f-06.webp",
      "alt": "找到“应用”",
      "caption": "找到“应用”",
      "source": "1-1.安装M365应用套件.docx"
    },
    {
      "src": "/assets/sop/install-m365/install-m365-86b832f-07.webp",
      "alt": "搜索Teams并进入“高级选项”",
      "caption": "搜索Teams并进入“高级选项”",
      "source": "1-1.安装M365应用套件.docx"
    },
    {
      "src": "/assets/sop/install-m365/install-m365-86b832f-08.webp",
      "alt": "找到“登陆后运行”关闭即可",
      "caption": "找到“登陆后运行”关闭即可",
      "source": "1-1.安装M365应用套件.docx"
    }
  ],
  "office-sign-in": [
    {
      "src": "/assets/sop/office-sign-in/office-sign-in-73bb8cd-01.webp",
      "alt": "等待Office产品安装完成后，打开“开始菜单”，找到Microsoft Word/Excel/PowerPoint 任意一个应用并点击运行",
      "caption": "等待Office产品安装完成后，打开“开始菜单”，找到Microsoft Word/Excel/PowerPoint 任意一个应用并点击运行",
      "source": "2.Office365登录.docx"
    },
    {
      "src": "/assets/sop/office-sign-in/office-sign-in-73bb8cd-02.webp",
      "alt": "打开应用后会自动弹出窗口要求登录账号",
      "caption": "打开应用后会自动弹出窗口要求登录账号",
      "source": "2.Office365登录.docx"
    }
  ],
  "outlook": [
    {
      "src": "/assets/sop/outlook/outlook-85b8ba0-01.webp",
      "alt": "等待Office产品安装完成后，打开“开始菜单”，找到Outlook(Classic)点击运行",
      "caption": "等待Office产品安装完成后，打开“开始菜单”，找到Outlook(Classic)点击运行",
      "source": "3.Outlook邮箱登录.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-85b8ba0-02.webp",
      "alt": "若您没有使用过Outlook, 请根据以下指引配置。输入账号并点击“连接”",
      "caption": "若您没有使用过Outlook, 请根据以下指引配置。输入账号并点击“连接”",
      "source": "3.Outlook邮箱登录.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-85b8ba0-03.webp",
      "alt": "若您此前已经登陆过Outlook，打开outlook后点击右上角“文件”> “添加账户”",
      "caption": "若您此前已经登陆过Outlook，打开outlook后点击右上角“文件”> “添加账户”",
      "source": "3.Outlook邮箱登录.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-01.webp",
      "alt": "选择“完成”。",
      "caption": "选择“完成”。",
      "source": "5. Outlook使用指引.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-02.webp",
      "alt": "登录完成后，您即可在导航栏右侧看到您的个人邮箱及分所邮箱。",
      "caption": "登录完成后，您即可在导航栏右侧看到您的个人邮箱及分所邮箱。",
      "source": "5. Outlook使用指引.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-03.webp",
      "alt": "点击左上角“新建电子邮件”",
      "caption": "点击左上角“新建电子邮件”",
      "source": "5. Outlook使用指引.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-04.webp",
      "alt": "找到“选项” > “…” > “发件人”",
      "caption": "找到“选项” > “…” > “发件人”",
      "source": "5. Outlook使用指引.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-05.webp",
      "alt": "可以看到新增了“发件人”选项",
      "caption": "可以看到新增了“发件人”选项",
      "source": "5. Outlook使用指引.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-06.webp",
      "alt": "点击“发件人” > “其他电子邮件地址”>“发件人”，并找到分所邮件地址",
      "caption": "点击“发件人” > “其他电子邮件地址”>“发件人”，并找到分所邮件地址",
      "source": "5. Outlook使用指引.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-07.webp",
      "alt": "点击“确定”回到发送邮件窗口，即可选择其他邮箱地址发送邮件",
      "caption": "点击“确定”回到发送邮件窗口，即可选择其他邮箱地址发送邮件",
      "source": "5. Outlook使用指引.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-08.webp",
      "alt": "键入邮件后，选择“发送”。",
      "caption": "键入邮件后，选择“发送”。",
      "source": "5. Outlook使用指引.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-09.webp",
      "alt": "提及的联系人将添加到电子邮件或会议邀请的“收件人”行。",
      "caption": "提及的联系人将添加到电子邮件或会议邀请的“收件人”行。",
      "source": "5. Outlook使用指引.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-10.webp",
      "alt": "重点收件箱",
      "caption": "重点收件箱",
      "source": "5. Outlook使用指引.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-11.webp",
      "alt": "选择“保存并关闭”完成操作；如果是会议，则选择“发送”。",
      "caption": "选择“保存并关闭”完成操作；如果是会议，则选择“发送”。",
      "source": "5. Outlook使用指引.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-12.webp",
      "alt": "网格显示与会者有空的时间。 在会议请求的右侧，Outlook 将显示建议时间和冲突人数。",
      "caption": "网格显示与会者有空的时间。 在会议请求的右侧，Outlook 将显示建议时间和冲突人数。",
      "source": "5. Outlook使用指引.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-13.webp",
      "alt": "进入发件箱，找到你想要撤回的邮件双击打开",
      "caption": "进入发件箱，找到你想要撤回的邮件双击打开",
      "source": "5. Outlook使用指引.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-14.webp",
      "alt": "弹出单独邮件的窗口左上角点击“文件”，即可看到撤回选项。",
      "caption": "弹出单独邮件的窗口左上角点击“文件”，即可看到撤回选项。",
      "source": "5. Outlook使用指引.docx"
    },
    {
      "src": "/assets/sop/outlook/outlook-1c42b14-15.webp",
      "alt": "公司内部的用户联系人都已经保存，您可以直接输入部分或全部名字进行搜索。",
      "caption": "公司内部的用户联系人都已经保存，您可以直接输入部分或全部名字进行搜索。",
      "source": "5. Outlook使用指引.docx"
    }
  ],
  "teams": [
    {
      "src": "/assets/sop/teams/teams-cb793a8-01.webp",
      "alt": "OneDrive：访问最近使用的文件和 OneDrive 内容。",
      "caption": "OneDrive：访问最近使用的文件和 OneDrive 内容。",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-02.webp",
      "alt": "点击“聊天”>“新消息”。",
      "caption": "点击“聊天”>“新消息”。",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-03.webp",
      "alt": "输入联系人姓名，开始对话。",
      "caption": "输入联系人姓名，开始对话。",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-04.webp",
      "alt": "@提及：使用 @用户名 提醒对方。",
      "caption": "@提及：使用 @用户名 提醒对方。",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-05.webp",
      "alt": "文字格式：点击“格式”图标可添加标题、项目符号等。",
      "caption": "文字格式：点击“格式”图标可添加标题、项目符号等。",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-06.webp",
      "alt": "反应：对消息添加表情反馈。鼠标悬浮在消息上即可选择表情",
      "caption": "反应：对消息添加表情反馈。鼠标悬浮在消息上即可选择表情",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-07.webp",
      "alt": "反应：对消息添加表情反馈。鼠标悬浮在消息上即可选择表情",
      "caption": "反应：对消息添加表情反馈。鼠标悬浮在消息上即可选择表情",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-08.webp",
      "alt": "重要消息：发送一次消息可以持续提醒对方",
      "caption": "重要消息：发送一次消息可以持续提醒对方",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-09.webp",
      "alt": "重要消息：发送一次消息可以持续提醒对方",
      "caption": "重要消息：发送一次消息可以持续提醒对方",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-10.webp",
      "alt": "延时发送：可以设定定时发送指定消息（此功能需要Teams应用运行）",
      "caption": "延时发送：可以设定定时发送指定消息（此功能需要Teams应用运行）",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-11.webp",
      "alt": "延时发送：可以设定定时发送指定消息（此功能需要Teams应用运行）",
      "caption": "延时发送：可以设定定时发送指定消息（此功能需要Teams应用运行）",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-12.webp",
      "alt": "更多功能：右键选择消息即可看到更多功能（转发，引用，固定，翻译等）",
      "caption": "更多功能：右键选择消息即可看到更多功能（转发，引用，固定，翻译等）",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-13.webp",
      "alt": "选择翻译后即可看到消息被直接翻译为中文了。",
      "caption": "选择翻译后即可看到消息被直接翻译为中文了。",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-14.webp",
      "alt": "登录进入后可从“团队“看到自己所在的分所/部门团队",
      "caption": "登录进入后可从“团队“看到自己所在的分所/部门团队",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-15.webp",
      "alt": "各个分所的所有服务器文件均在此处可见",
      "caption": "各个分所的所有服务器文件均在此处可见",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-16.webp",
      "alt": "在“日历”中点击“新事件”> “事件”。",
      "caption": "在“日历”中点击“新事件”> “事件”。",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-17.webp",
      "alt": "填写会议主题、时间、参与者等信息。可选择是否添加 Teams 会议链接。",
      "caption": "填写会议主题、时间、参与者等信息。可选择是否添加 Teams 会议链接。",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-18.webp",
      "alt": "输入参会人员后，可以查阅参会人员该时间段是否有其他Teams会议。",
      "caption": "输入参会人员后，可以查阅参会人员该时间段是否有其他Teams会议。",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-19.webp",
      "alt": "此处可见在该时间段，对方有其他会议。进一步点击“日程安排助理”即可看到对方具体的会议时间，以便修改会议时间",
      "caption": "此处可见在该时间段，对方有其他会议。进一步点击“日程安排助理”即可看到对方具体的会议时间，以便修改会议时间",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-20.webp",
      "alt": "在“日历”中点击会议条目，选择“加入”。或根据自己的具体安排选择接受、拒绝、待定。",
      "caption": "在“日历”中点击会议条目，选择“加入”。或根据自己的具体安排选择接受、拒绝、待定。",
      "source": "6.Teams使用指引.docx"
    },
    {
      "src": "/assets/sop/teams/teams-cb793a8-21.webp",
      "alt": "加入前可选择使用音频、视频、背景模糊等设置。",
      "caption": "加入前可选择使用音频、视频、背景模糊等设置。",
      "source": "6.Teams使用指引.docx"
    }
  ],
  "onedrive": [
    {
      "src": "/assets/sop/onedrive/onedrive-672744b-01.webp",
      "alt": "建议勾选“让我使用OneDrive获取我电脑上的文件”（方便备份桌面/文档）。",
      "caption": "建议勾选“让我使用OneDrive获取我电脑上的文件”（方便备份桌面/文档）。",
      "source": "7.OneDrive使用指引.docx"
    },
    {
      "src": "/assets/sop/onedrive/onedrive-672744b-02.webp",
      "alt": "电脑本地：\n直接拖拽文件到“OneDrive”文件夹（路径：文件资源管理器左侧导航栏）。",
      "caption": "电脑本地：\n直接拖拽文件到“OneDrive”文件夹（路径：文件资源管理器左侧导航栏）。",
      "source": "7.OneDrive使用指引.docx"
    },
    {
      "src": "/assets/sop/onedrive/onedrive-672744b-03.webp",
      "alt": "右键点击文件 → 选择“下载”（网页版）或“始终保留在此设备上”（本地同步）。",
      "caption": "右键点击文件 → 选择“下载”（网页版）或“始终保留在此设备上”（本地同步）。",
      "source": "7.OneDrive使用指引.docx"
    },
    {
      "src": "/assets/sop/onedrive/onedrive-672744b-04.webp",
      "alt": "键点击文件 → 选择“共享” → 输入同事邮箱或选择“公司内部可编辑/仅查看” → 点击“发送”。",
      "caption": "键点击文件 → 选择“共享” → 输入同事邮箱或选择“公司内部可编辑/仅查看” → 点击“发送”。",
      "source": "7.OneDrive使用指引.docx"
    },
    {
      "src": "/assets/sop/onedrive/onedrive-672744b-05.webp",
      "alt": "高级设置：可设置密码/过期时间。点击复制链接旁的齿轮按钮",
      "caption": "高级设置：可设置密码/过期时间。点击复制链接旁的齿轮按钮",
      "source": "7.OneDrive使用指引.docx"
    },
    {
      "src": "/assets/sop/onedrive/onedrive-672744b-06.webp",
      "alt": "OneDrive中自动生成文件夹：OneDrive会根据您的使用自动生成不同的文件夹最为常见的如下",
      "caption": "OneDrive中自动生成文件夹：OneDrive会根据您的使用自动生成不同的文件夹最为常见的如下",
      "source": "7.OneDrive使用指引.docx"
    },
    {
      "src": "/assets/sop/onedrive/onedrive-672744b-07.webp",
      "alt": "点击邮件中的Open：",
      "caption": "点击邮件中的Open：",
      "source": "7.OneDrive使用指引.docx"
    },
    {
      "src": "/assets/sop/onedrive/onedrive-672744b-08.webp",
      "alt": "进入页面后选择点击同步（Sync）即可将文件保留在本地",
      "caption": "进入页面后选择点击同步（Sync）即可将文件保留在本地",
      "source": "7.OneDrive使用指引.docx"
    }
  ],
  "scan-documents": [
    {
      "src": "/assets/sop/scan-documents/scan-documents-3a4bad4-01.webp",
      "alt": "如您在更多中没有找到文档矫正，请在更多中点击，下载文档矫正。",
      "caption": "如您在更多中没有找到文档矫正，请在更多中点击，下载文档矫正。",
      "source": "NAS服务器文件夹（扫描Scan文件夹）访问配置.docx"
    }
  ],
  "sharepoint": [
    {
      "src": "/assets/sop/sharepoint/sharepoint-b1e2321-01.webp",
      "alt": "登录后，您将看到 SharePoint 起始页：",
      "caption": "登录后，您将看到 SharePoint 起始页：",
      "source": "使用 SharePoint 共享文件指引.docx"
    },
    {
      "src": "/assets/sop/sharepoint/sharepoint-b1e2321-02.webp",
      "alt": "如果浏览器弹出提示，允许 OneDrive 打开，请点击允许。",
      "caption": "如果浏览器弹出提示，允许 OneDrive 打开，请点击允许。",
      "source": "使用 SharePoint 共享文件指引.docx"
    },
    {
      "src": "/assets/sop/sharepoint/sharepoint-b1e2321-03.webp",
      "alt": "打开任意文件夹即可看到此共享文件夹",
      "caption": "打开任意文件夹即可看到此共享文件夹",
      "source": "使用 SharePoint 共享文件指引.docx"
    },
    {
      "src": "/assets/sop/sharepoint/sharepoint-b1e2321-04.webp",
      "alt": "绿色勾号：已成功同步。",
      "caption": "绿色勾号：已成功同步。",
      "source": "使用 SharePoint 共享文件指引.docx"
    },
    {
      "src": "/assets/sop/sharepoint/sharepoint-b1e2321-05.webp",
      "alt": "蓝色云朵：仅联机文件（未下载到本地，但占用空间小）。",
      "caption": "蓝色云朵：仅联机文件（未下载到本地，但占用空间小）。",
      "source": "使用 SharePoint 共享文件指引.docx"
    },
    {
      "src": "/assets/sop/sharepoint/sharepoint-b1e2321-06.webp",
      "alt": "蓝色圈圈：文件正在同步中。",
      "caption": "蓝色圈圈：文件正在同步中。",
      "source": "使用 SharePoint 共享文件指引.docx"
    },
    {
      "src": "/assets/sop/sharepoint/sharepoint-b1e2321-07.webp",
      "alt": "红色圆圈：同步错误，需点击检查。",
      "caption": "红色圆圈：同步错误，需点击检查。",
      "source": "使用 SharePoint 共享文件指引.docx"
    }
  ],
  "first-sign-in": [
    {
      "src": "/assets/sop/branch-account/branch-account-15ce775-01.webp",
      "alt": "输入您的账号user@example.com",
      "caption": "输入您的账号user@example.com",
      "source": "分所账号配置.docx"
    },
    {
      "src": "/assets/sop/branch-account/branch-account-15ce775-02.webp",
      "alt": "安卓下载“腾讯身份验证器”：https://sj.qq.com/appdetail/com.tencent.authenticator（您需要先安装腾讯应用宝）",
      "caption": "安卓下载“腾讯身份验证器”：https://sj.qq.com/appdetail/com.tencent.authenticator（您需要先安装腾讯应用宝）",
      "source": "分所账号配置.docx"
    },
    {
      "src": "/assets/sop/branch-account/branch-account-15ce775-03.webp",
      "alt": "苹果应用商店下载“Microsoft Authenticator”(请认真辨别应用)",
      "caption": "苹果应用商店下载“Microsoft Authenticator”(请认真辨别应用)",
      "source": "分所账号配置.docx"
    },
    {
      "src": "/assets/sop/branch-account/branch-account-15ce775-04.webp",
      "alt": "回到电脑上，请访问“安全信息”栏-“更新信息”",
      "caption": "回到电脑上，请访问“安全信息”栏-“更新信息”",
      "source": "分所账号配置.docx"
    },
    {
      "src": "/assets/sop/branch-account/branch-account-15ce775-05.webp",
      "alt": "点击“添加登陆方法” > 添加“Microsoft Authenticator”并添加您的手机应用作为登录验证方式",
      "caption": "点击“添加登陆方法” > 添加“Microsoft Authenticator”并添加您的手机应用作为登录验证方式",
      "source": "分所账号配置.docx"
    },
    {
      "src": "/assets/sop/branch-account/branch-account-15ce775-06.webp",
      "alt": "苹果手机直接点击“下一步”",
      "caption": "苹果手机直接点击“下一步”",
      "source": "分所账号配置.docx"
    },
    {
      "src": "/assets/sop/branch-account/branch-account-15ce775-07.webp",
      "alt": "在手机应用Microsoft Authenticator上，点击右上角+号，选择“工作或学校账户”，然后选择“扫描QR码”，并扫描上一步中的二维码",
      "caption": "在手机应用Microsoft Authenticator上，点击右上角+号，选择“工作或学校账户”，然后选择“扫描QR码”，并扫描上一步中的二维码",
      "source": "分所账号配置.docx"
    },
    {
      "src": "/assets/sop/branch-account/branch-account-15ce775-08.webp",
      "alt": "安卓手机选择“我想要使用其他身份验证器应用”",
      "caption": "安卓手机选择“我想要使用其他身份验证器应用”",
      "source": "分所账号配置.docx"
    },
    {
      "src": "/assets/sop/branch-account/branch-account-15ce775-09.webp",
      "alt": "选择扫描二维码，并扫描电脑上二维码，您即可看到手机上的6位数字如下",
      "caption": "选择扫描二维码，并扫描电脑上二维码，您即可看到手机上的6位数字如下",
      "source": "分所账号配置.docx"
    },
    {
      "src": "/assets/sop/branch-account/branch-account-15ce775-10.webp",
      "alt": "选择扫描二维码，并扫描电脑上二维码，您即可看到手机上的6位数字如下",
      "caption": "选择扫描二维码，并扫描电脑上二维码，您即可看到手机上的6位数字如下",
      "source": "分所账号配置.docx"
    }
  ],
  "password-reset": [
    {
      "src": "/assets/sop/password-reset/password-reset-c20e255-01.webp",
      "alt": "手机浏览器访问Microsoft Online Password Reset （https:// passwordreset.microsoftonline.com）",
      "caption": "手机浏览器访问Microsoft Online Password Reset （https:// passwordreset.microsoftonline.com）",
      "source": "自主重置公司账号密码.docx"
    },
    {
      "src": "/assets/sop/password-reset/password-reset-c5b3f41-01.webp",
      "alt": "点击下方无法访问账号",
      "caption": "点击下方无法访问账号",
      "source": "自助修改密码.docx"
    },
    {
      "src": "/assets/sop/password-reset/password-reset-c5b3f41-02.webp",
      "alt": "等待界面跳转，输入你的账号（user@example.com）及验证码。随后点击下一步。",
      "caption": "等待界面跳转，输入你的账号（user@example.com）及验证码。随后点击下一步。",
      "source": "自助修改密码.docx"
    },
    {
      "src": "/assets/sop/password-reset/password-reset-c5b3f41-03.webp",
      "alt": "进入页面后有多个选项：手机号码/邮箱/验证器/办公室电话。请在里面选择任意两种方式验证",
      "caption": "进入页面后有多个选项：手机号码/邮箱/验证器/办公室电话。请在里面选择任意两种方式验证",
      "source": "自助修改密码.docx"
    }
  ],
  "security-info": [
    {
      "src": "/assets/sop/security-info/security-info-896edd9-01.webp",
      "alt": "在主页找到“安全信息”，点击卡片中的“更新信息”。",
      "caption": "在主页找到“安全信息”，点击卡片中的“更新信息”。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-02.webp",
      "alt": "点击“添加登录方法”，在弹出的窗口中选择“电话”。",
      "caption": "点击“添加登录方法”，在弹出的窗口中选择“电话”。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-03.webp",
      "alt": "先选择号码所属国家或地区，再输入手机号码；确认已选择“呼叫我”，然后点击“下一步”。",
      "caption": "先选择号码所属国家或地区，再输入手机号码；确认已选择“呼叫我”，然后点击“下一步”。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-04.webp",
      "alt": "浏览器显示“呼叫已应答，你的电话号码已成功注册”后，点击“完成”。",
      "caption": "浏览器显示“呼叫已应答，你的电话号码已成功注册”后，点击“完成”。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-05.webp",
      "alt": "在 App Store 搜索“Microsoft Authenticator”或“微软验证器”并完成安装。回到浏览器，选择 Microsoft Authenticator，然后点击“下一步”。",
      "caption": "在 App Store 搜索“Microsoft Authenticator”或“微软验证器”并完成安装。回到浏览器，选择 Microsoft Authenticator，然后点击“下一步”。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-06.webp",
      "alt": "打开 Microsoft Authenticator，点击右上角“+”，选择“工作或学校账户”，再选择“扫描 QR 码”。",
      "caption": "打开 Microsoft Authenticator，点击右上角“+”，选择“工作或学校账户”，再选择“扫描 QR 码”。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-07.webp",
      "alt": "浏览器再次点击“下一步”后会显示二维码。使用手机中的 Microsoft Authenticator 扫描该二维码，然后回到电脑点击“下一步”。",
      "caption": "浏览器再次点击“下一步”后会显示二维码。使用手机中的 Microsoft Authenticator 扫描该二维码，然后回到电脑点击“下一步”。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-08.webp",
      "alt": "电脑网页会显示一个数字；手机同时弹出批准登录的窗口。在手机中输入网页上的数字，再点击“是”或批准。",
      "caption": "电脑网页会显示一个数字；手机同时弹出批准登录的窗口。在手机中输入网页上的数字，再点击“是”或批准。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-09.webp",
      "alt": "电脑网页会显示一个数字；手机同时弹出批准登录的窗口。在手机中输入网页上的数字，再点击“是”或批准。",
      "caption": "电脑网页会显示一个数字；手机同时弹出批准登录的窗口。在手机中输入网页上的数字，再点击“是”或批准。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-10.webp",
      "alt": "电脑网页会显示一个数字；手机同时弹出批准登录的窗口。在手机中输入网页上的数字，再点击“是”或批准。",
      "caption": "电脑网页会显示一个数字；手机同时弹出批准登录的窗口。在手机中输入网页上的数字，再点击“是”或批准。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-11.webp",
      "alt": "在 Microsoft Authenticator 设置页面点击“我想要使用其他身份验证器”，再点击“下一步”。",
      "caption": "在 Microsoft Authenticator 设置页面点击“我想要使用其他身份验证器”，再点击“下一步”。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-12.webp",
      "alt": "在 Microsoft Authenticator 设置页面点击“我想要使用其他身份验证器”，再点击“下一步”。",
      "caption": "在 Microsoft Authenticator 设置页面点击“我想要使用其他身份验证器”，再点击“下一步”。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-13.webp",
      "alt": "在腾讯身份验证器中选择扫描二维码，扫描电脑上显示的二维码。扫描成功后，手机会显示 6 位动态数字。",
      "caption": "在腾讯身份验证器中选择扫描二维码，扫描电脑上显示的二维码。扫描成功后，手机会显示 6 位动态数字。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-14.webp",
      "alt": "在腾讯身份验证器中选择扫描二维码，扫描电脑上显示的二维码。扫描成功后，手机会显示 6 位动态数字。",
      "caption": "在腾讯身份验证器中选择扫描二维码，扫描电脑上显示的二维码。扫描成功后，手机会显示 6 位动态数字。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-15.webp",
      "alt": "回到电脑点击“下一步”，输入手机验证器中当前显示的 6 位数字，再点击“下一步”。数字会定时更新，请输入仍在有效期内的数字。",
      "caption": "回到电脑点击“下一步”，输入手机验证器中当前显示的 6 位数字，再点击“下一步”。数字会定时更新，请输入仍在有效期内的数字。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-16.webp",
      "alt": "回到电脑点击“下一步”，输入手机验证器中当前显示的 6 位数字，再点击“下一步”。数字会定时更新，请输入仍在有效期内的数字。",
      "caption": "回到电脑点击“下一步”，输入手机验证器中当前显示的 6 位数字，再点击“下一步”。数字会定时更新，请输入仍在有效期内的数字。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-17.webp",
      "alt": "https://myaccount.microsoft.com",
      "caption": "https://myaccount.microsoft.com",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    },
    {
      "src": "/assets/sop/security-info/security-info-896edd9-18.webp",
      "alt": "在“新密码”和“确认新密码”中输入同一个新密码。满足页面显示的密码要求后，点击“提交”。",
      "caption": "在“新密码”和“确认新密码”中输入同一个新密码。满足页面显示的密码要求后，点击“提交”。",
      "source": "4.添加账号验证方式及修改密码（优化版）.docx"
    }
  ]
};
